version: "3.8"
services:
  postgres:
    container_name: tools-database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tools
      POSTGRES_DB: tools-database
    volumes:
      - pgdata:/data/postgres
    ports:
      - 5432:5432
  app:
    container_name: api-tools
    image: node:18
    working_dir: /usr/app
    command: bash -c "npm install && npm run start:dev"
    environment:
      DATABASE_URL: postgresql://postgres:tools@postgres:5432/tools-database?schema=public
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - postgres

volumes:
    pgdata:
        driver: local