version: "3.8"
services:
  postgres:
    container_name: tools-database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tools
      POSTGRES_DB: tools-database
    volumes:
      - pgdata:/data/postgres
    ports:
      - 5432:5432
volumes:
    pgdata:
        driver: local